# Recursive algorithm training

# 3x3 sudoku

In [12]:
import numpy as np
a = np.matrix([[1,3,0],[0,2,1],[0,0,0]])

In [13]:
print(a)

[[1 3 0]
 [0 2 1]
 [0 0 0]]


In [14]:
list = [i for i in range(1,len(a)+1)]
# possible = []
b = np.zeros((len(a),len(a)))

def solve(a):
    solved =True
    for i in range(len(a)):
        for j in range(len(a)):
            if a[i,j]==0:
                maybe = [x for x in list if x not in a[i,:] and x not in a[:,j]]
#                 possible.append(maybe)
                if len(maybe)==1:
                    b[i,j] = maybe[0]
                else:
                    solved = False
            else:
                b[i,j] = a[i,j]
#                 possible.append([])
    if solved == False:
        solve(b)
    else:
        return b
    return b

In [15]:
solve(a)

array([[1., 3., 2.],
       [3., 2., 1.],
       [2., 1., 3.]])

# 4x4 Sudoku

In [16]:
a = np.matrix([[0,0,3,0],[0,1,0,0],[2,0,0,3],[0,0,0,4]])

In [17]:
print(a)

[[0 0 3 0]
 [0 1 0 0]
 [2 0 0 3]
 [0 0 0 4]]


In [18]:
list = [i for i in range(1,len(a)+1)]
# possible = []
b = np.zeros((len(a),len(a)))

def checkgrid(a,i,j):
    if (i<2) and (j<2):
        m,n = [0,1],[0,1]
    if (i<2) and (j>1):
        m,n = [0,1],[2,3]
    if (i>1) and (j<2):
        m,n = [2,3],[0,1]
    if (i>1) and (j>1):
        m,n = [2,3],[2,3]
    grid=[]
    for k in m:
        for l in n:
            grid.append(a[k,l])
    return grid

def solve4x4(a):
    solved =True
    for i in range(len(a)):
        for j in range(len(a)):
            if a[i,j]==0:
                grid = checkgrid(a,i,j)
                maybe = [x for x in list if x not in a[i,:] and x not in a[:,j] and x not in grid]
#                 possible.append(maybe)
                if len(maybe)==1:
                    b[i,j] = maybe[0]
                else:
                    solved = False
            else:
                b[i,j] = a[i,j]
#                 possible.append([])
    if solved == False:
        solve4x4(b)
    else:
        return b
    return b

In [19]:
b=solve4x4(a)
print(b)
# print(possible)

[[4. 2. 3. 1.]
 [3. 1. 4. 2.]
 [2. 4. 1. 3.]
 [1. 3. 2. 4.]]


# 9x9 sudoku

In [21]:
import numpy as np
#a = np.matrix([[5,1,7,6,0,0,0,3,4],[2,8,9,0,0,4,0,0,0],[3,4,6,2,0,5,0,9,0],[6,0,2,0,0,0,0,1,0],[0,3,8,0,0,6,0,4,7],[0,0,0,0,0,0,0,0,0],[0,9,0,0,0,0,0,7,8],[7,0,3,4,0,0,5,6,0],[0,0,0,0,0,0,0,0,0]])
a = np.matrix([[5,3,0,0,7,0,0,0,0],[6,0,0,1,9,5,0,0,0],[0,9,8,0,0,0,0,6,0],[8,0,0,0,6,0,0,0,3],[4,0,0,8,0,3,0,0,1],[7,0,0,0,2,0,0,0,6],[0,6,0,0,0,0,2,8,0],[0,0,0,4,1,9,0,0,5],[0,0,0,0,8,0,0,7,9]])

In [22]:
print(a)

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [23]:
# make output matrix
b = np.zeros((len(a),len(a))) # 9x9 matrix of zeros

def solve9x9(a):
    """
    main program
    
    """
    solved = True  # variable explaining puzzle condition. if
                   # there is one cell containing more than one
                   # possible number, this variable will be "False"
            
    
    # call is_Solved function to check whether the puzzle is solved
    b,solved = is_Solved(a,solved)
    
    # if the puzzle has not been solved, then the function calls
    # itself to solve the puzzle recursively using updated puzzle
    if solved == False:
        solve9x9(b)
        
    # if the puzzle is solved, return the output
    else:
        return b
    return b
    

def is_Solved(a,solved):
    """
    function to fill and check whether the puzzle has been solved
    
    """

    # check every cell in input matrix
    for i in range(len(a)):
        for j in range(len(a)):
            
            # if cell is empty, we will find the possible number
            if a[i,j]==0:
                # make array of possible number
                possiblenum = getpossiblenum(a,i,j) 
                
                # if there is only one possible number, fill the output
                if len(possiblenum)==1:
                    b[i,j] = possiblenum[0] 
                                            
                # if possible number > 1, puzzle is not solved         
                else:
                    solved = False
            
            # if cell contains number, fill output with that number
            else:
                b[i,j] = a[i,j]
                
    return b,solved

def getpossiblenum(a,i,j):
    """
    function to make an array of possible number(s) of one cell.
    
    """
    
    # get grid location based on i and j
    if (i<3) and (j<3):
        m,n = [0,1,2],[0,1,2]
    if (2<i<6) and (j<3):
        m,n = [3,4,5],[0,1,2]
    if (5<i<9) and (j<3):
        m,n = [6,7,8],[0,1,2]
        
    if (i<3) and (2<j<6):
        m,n = [0,1,2],[3,4,5]
    if (2<i<6) and (2<j<6):
        m,n = [3,4,5],[3,4,5]
    if (5<i<9) and (2<j<6):
        m,n = [6,7,8],[3,4,5]
        
    if (i<3) and (5<j<9):
        m,n = [0,1,2],[6,7,8]
    if (2<i<6) and (5<j<9):
        m,n = [3,4,5],[6,7,8]
    if (5<i<9) and (5<j<9):
        m,n = [6,7,8],[6,7,8]
        
    # fill the grid array with all number in respective grid
    grid=[]
    for k in m:
        for l in n:
            grid.append(a[k,l])
    
    # assign necessary variable
    list = [i for i in range(1,len(a)+1)] # array of number 1-9
    
    # Make array consisting all possible numbers in one cell.
    # Criteria : number in range 1-9 which is not present in 
    # grid array, horizontal, and vertical lines
    possiblenum = [x for x in list if x not in a[i,:] 
                   and x not in a[:,j] and x not in grid]        
    
    return possiblenum



In [24]:
b=solve9x9(a)
print(b)

[[5. 3. 4. 6. 7. 8. 9. 1. 2.]
 [6. 7. 2. 1. 9. 5. 3. 4. 8.]
 [1. 9. 8. 3. 4. 2. 5. 6. 7.]
 [8. 5. 9. 7. 6. 1. 4. 2. 3.]
 [4. 2. 6. 8. 5. 3. 7. 9. 1.]
 [7. 1. 3. 9. 2. 4. 8. 5. 6.]
 [9. 6. 1. 5. 3. 7. 2. 8. 4.]
 [2. 8. 7. 4. 1. 9. 6. 3. 5.]
 [3. 4. 5. 2. 8. 6. 1. 7. 9.]]
